// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkjvvqbbbrosoeyhrcux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRranZ2cWJiYnJvc29leWhyY3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDM1OTcsImV4cCI6MjA1NTYxOTU5N30.3YZs7KfdzLcm0zo6YI7HLX__lV_v6NClrQXHBsMNKkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);